"""auto

Revision ID: 7b95a733a15f
Revises: 
Create Date: 2020-07-15 09:30:59.027541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b95a733a15f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
        sa.UniqueConstraint("username", name=op.f("uq__user__username")),
    )
    op.create_table(
        "followers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_user", sa.Integer(), nullable=False),
        sa.Column("to_user", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_user"],
            ["user.id"],
            name=op.f("fk__followers__from_user__user"),
        ),
        sa.ForeignKeyConstraint(
            ["to_user"], ["user.id"], name=op.f("fk__followers__to_user__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__followers")),
    )
    op.create_index(
        op.f("ix__followers__from_user"),
        "followers",
        ["from_user"],
        unique=False,
    )
    op.create_index(
        op.f("ix__followers__to_user"), "followers", ["to_user"], unique=False
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk__post__user_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__post")),
    )
    op.create_index(
        op.f("ix__post__timestamp"), "post", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix__post__user_id"), "post", ["user_id"], unique=False
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"], ["post.id"], name=op.f("fk__comment__post_id__post")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk__comment__user_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__comment")),
    )
    op.create_index(
        op.f("ix__comment__post_id"), "comment", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix__comment__timestamp"), "comment", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix__comment__user_id"), "comment", ["user_id"], unique=False
    )
    op.create_table(
        "like",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["post.id"], name=op.f("fk__like__post_id__post")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk__like__user_id__user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__like")),
    )
    op.create_index(
        op.f("ix__like__post_id"), "like", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix__like__user_id"), "like", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__like__user_id"), table_name="like")
    op.drop_index(op.f("ix__like__post_id"), table_name="like")
    op.drop_table("like")
    op.drop_index(op.f("ix__comment__user_id"), table_name="comment")
    op.drop_index(op.f("ix__comment__timestamp"), table_name="comment")
    op.drop_index(op.f("ix__comment__post_id"), table_name="comment")
    op.drop_table("comment")
    op.drop_index(op.f("ix__post__user_id"), table_name="post")
    op.drop_index(op.f("ix__post__timestamp"), table_name="post")
    op.drop_table("post")
    op.drop_index(op.f("ix__followers__to_user"), table_name="followers")
    op.drop_index(op.f("ix__followers__from_user"), table_name="followers")
    op.drop_table("followers")
    op.drop_table("user")
    # ### end Alembic commands ###
